### ISSUE TITLE
make error with FMT_STRING

### ISSUE THREAD

**Issue by MaximeGonthier** [schnorr/pajeng#32] opened 2021-05-18 11:56 UTC
Hello,

I would like to use starvz. So, I am installing pajeng for pj_dump.

I have installed build-essential libboost-dev asciidoc flex bison libfmt-dev.

After the cmake .., I get with make install the following error: 

:~/pajeng/b$ make install
[  3%] Building CXX object src/libpaje/CMakeFiles/paje_library.dir/PajeEntity.cc.o
/home/gonthier/pajeng/src/libpaje/PajeEntity.cc: In function ‘std::__cxx11::string ToStringFixedKarma(double, unsigned int)’:
/home/gonthier/pajeng/src/libpaje/PajeEntity.cc:49:22: error: ‘FMT_STRING’ was not declared in this scope
   return fmt::format(FMT_STRING("{:.{}f}"), d, width);
                      ^~~~~~~~~~
/home/gonthier/pajeng/src/libpaje/PajeEntity.cc:49:22: note: suggested alternative: ‘__STRING’
   return fmt::format(FMT_STRING("{:.{}f}"), d, width);
                      ^~~~~~~~~~
                      __STRING
src/libpaje/CMakeFiles/paje_library.dir/build.make:409: recipe for target 'src/libpaje/CMakeFiles/paje_library.dir/PajeEntity.cc.o' failed
make[2]: *** [src/libpaje/CMakeFiles/paje_library.dir/PajeEntity.cc.o] Error 1
CMakeFiles/Makefile2:106: recipe for target 'src/libpaje/CMakeFiles/paje_library.dir/all' failed
make[1]: *** [src/libpaje/CMakeFiles/paje_library.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

Did I forget something ? 
Thanks you in advance

**Comment by schnorr** [comment] 2021-05-18 18:37
Hi @MaximeGonthier, thanks a lot for giving pajeng a try. I've tried to reproduce the problem here by manually installing the three versions (7.1.1, 7.1.2, 7.1.3) listed in the [fmt.dev](https://fmt.dev/). I've configured and installed each version with the command `cmake -DCMAKE_INSTALL_PREFIX=/tmp/install -DBUILD_SHARED_LIBS=TRUE -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE ..` and then pointed pajeng cmake to the right libfmt, in the right place, with `cmake -DCMAKE_PREFIX_PATH=/tmp/install .`. It turns out that I was incapable to reproduce your problem with the latest version of `libfmt`. So, I've tried with older versions of `libfmt` listed in their [github codebase](https://github.com/fmtlib/fmt/releases/). I was capable to reproduce your problem with version `4.0.0`, so I think the problem is that your libfmt is outdated. Here's my output:

```
[ 76%] Building CXX object src/libpaje/CMakeFiles/paje_library.dir/PajeEntity.cc.o
/home/schnorr/dev/pajeng/src/libpaje/PajeEntity.cc: In function ‘std::string ToStringFixedKarma(double, unsigned int)’:
/home/schnorr/dev/pajeng/src/libpaje/PajeEntity.cc:49:22: error: ‘FMT_STRING’ was not declared in this scope; did you mean ‘FMT_NARG’?
   49 |   return fmt::format(FMT_STRING("{:.{}f}"), d, width);
      |                      ^~~~~~~~~~
      |                      FMT_NARG
make[2]: *** [src/libpaje/CMakeFiles/paje_library.dir/build.make:275: src/libpaje/CMakeFiles/paje_library.dir/PajeEntity.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:154: src/libpaje/CMakeFiles/paje_library.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
```


My tests indicate that pajeng compiles fine against version `5.0.0` (which is itself pretty old already).
**Is it possible to upgrade your `libfmt` to a more recent version?**

**Comment by schnorr** [comment] 2021-05-18 18:47
Commit 579facc859c10641187ef1f75a6f21144c066ce5 forces the libfmt version to be at least `5.0.0` and on. I am closing this issue, feel free @MaximeGonthier to open it if the problem remains. Thank you.

**Closed by schnorr** 2021-05-18 18:47 UTC

**Comment by MaximeGonthier** [comment] 2021-05-19 10:11
Hello. Thank you, yes I had an outdated version of fmt.

However I am getting a new issue with make install:

[  3%] [BISON][parser] Building parser with bison 3.0.4
[  6%] [FLEX][scanner] Building scanner with flex 2.5.39
Scanning dependencies of target paje_library
[ 10%] Building CXX object src/libpaje/CMakeFiles/paje_library.dir/PajeEventDefinition.cc.o
[ 13%] Building CXX object src/libpaje/CMakeFiles/paje_library.dir/PajeTraceEvent.cc.o
[ 16%] Building CXX object src/libpaje/CMakeFiles/paje_library.dir/PajeEvent.cc.o
[ 20%] Building CXX object src/libpaje/CMakeFiles/paje_library.dir/PajeData.cc.o
[ 23%] Building CXX object src/libpaje/CMakeFiles/paje_library.dir/PajeFileReader.cc.o
[ 26%] Building CXX object src/libpaje/CMakeFiles/paje_library.dir/PajeObject.cc.o
[ 30%] Building CXX object src/libpaje/CMakeFiles/paje_library.dir/PajeEventDecoder.cc.o
[ 33%] Building CXX object src/libpaje/CMakeFiles/paje_library.dir/PajeSimulator.cc.o
[ 36%] Building CXX object src/libpaje/CMakeFiles/paje_library.dir/PajeProbabilisticSimulator.cc.o
[ 40%] Building CXX object src/libpaje/CMakeFiles/paje_library.dir/PajeSimulator+Queries.cc.o
[ 43%] Building CXX object src/libpaje/CMakeFiles/paje_library.dir/PajeSimulator+Commands.cc.o
[ 46%] Building CXX object src/libpaje/CMakeFiles/paje_library.dir/PajeComponent.cc.o
[ 50%] Building CXX object src/libpaje/CMakeFiles/paje_library.dir/PajeType.cc.o
[ 53%] Building CXX object src/libpaje/CMakeFiles/paje_library.dir/PajeValue.cc.o
[ 56%] Building CXX object src/libpaje/CMakeFiles/paje_library.dir/PajeEntity.cc.o
[ 60%] Building CXX object src/libpaje/CMakeFiles/paje_library.dir/PajeContainer.cc.o
[ 63%] Building CXX object src/libpaje/CMakeFiles/paje_library.dir/PajeColor.cc.o
[ 66%] Building CXX object src/libpaje/CMakeFiles/paje_library.dir/PajeException.cc.o
[ 70%] Building CXX object src/libpaje/CMakeFiles/paje_library.dir/PajeDefinitions.cc.o
[ 73%] Building CXX object src/libpaje/CMakeFiles/paje_library.dir/lexer.cc.o
[ 76%] Building CXX object src/libpaje/CMakeFiles/paje_library.dir/parser.cc.o
[ 80%] Building CXX object src/libpaje/CMakeFiles/paje_library.dir/PajeFlexReader.cc.o
[ 83%] Building CXX object src/libpaje/CMakeFiles/paje_library.dir/PajeUnity.cc.o
[ 86%] Linking CXX shared library libpaje.so
/usr/bin/ld: /usr/local/lib/libfmt.a(format.cc.o): relocation R_X86_64_PC32 against symbole `_ZTVN3fmt2v712format_errorE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld : échec de l'édition de liens finale : Mauvaise valeur
collect2: error: ld returned 1 exit status
src/libpaje/CMakeFiles/paje_library.dir/build.make:679: recipe for target 'src/libpaje/libpaje.so.1.3' failed
make[2]: *** [src/libpaje/libpaje.so.1.3] Error 1
CMakeFiles/Makefile2:106: recipe for target 'src/libpaje/CMakeFiles/paje_library.dir/all' failed
make[1]: *** [src/libpaje/CMakeFiles/paje_library.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by schnorr** [comment] 2021-05-20 02:39
Hi @MaximeGonthier, that's because you need to compile `libfmt` as a shared library (the default is static, as you saw in your log `/usr/local/lib/libfmt.a`) with position independent code. As in my previous message you can do that by configuring `libfmt` with `cmake -DCMAKE_INSTALL_PREFIX=/tmp/install -DBUILD_SHARED_LIBS=TRUE -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE ..` and then proceeding to compilation, installation, etc. Let me know if that doesn't work for you.

**Comment by MaximeGonthier** [comment] 2021-05-25 16:33
Ah yes it was that. 

Thanks a lot!
